export class Select2APIEndpoint {
  static readonly Select2 = {
    GetEntitySelect2List: '/Entity/GetSelect2List',
    GetApPymentTypeSelect2List: '/Lookup/ApPaymentType',
    GetApVendorSelect2List: '/ApVendor/GetVendorSelect2List',
    GetArMiscStatusSelect2List: '/Lookup/ArMiscPosted',
    GetSpBenSelect2List: '/SpBeneficents/GetSpBeneficentsSelect2List',
    GetProjectNameSelect2List: '/ScProject/GetScProjectSelect2List',
    GetCollectorsSelect2List: '/ApMiscPaymentHeader/GetCollectorsSelect2List',
    GetvendorSelect2List: '/ApVendor/GetvendorSelect2List',
    ReceiptIdentifierSelect2List: '/Lookup/ReceiptIdentifier',
    GetFndCountrySelect2List: '/FndCountry/GetSelect2List',
    GetBranchSelect2List: '/GlAccDetails/select2',
    GetDepartmentSelect2List: '/Department/Select2',
    GetGlAccountSelect2List: '/GlAccount/GetGlAccountSelect2List',
    GetSpBeneficentsSelect2List: '/SpBeneficents/GetSpBeneficentsSelect2List',
    GetGlPeriodDetailSelect2List: '/GlPeriodDetails/GetGlPeriodDetailSelect2List',
    GetInvoiceTypeSelect2List: '/VwApInvoiceHd/GetInvoiceTypeSelect2List',
    GetMiscPaymentStatusSelect2List: '/Lookup/Posted',
    GetApVendorStatusSelect2List: '/Lookup/ApVendorStatus',
    GetJvSourceSelect2List: '/Lookup/JvSource',
    GetJeStatusSelect2List: '/Lookup/JeStatus',
    GetCurrencySelect2List: '/Lookup/Currency',
    SpOfficesSelect2List: '/Lookup/SpOffices',
    SpCasesPaymentSelect2List: '/SpCasesPayment/GetSpCasesPaymentSelect2List',
    PaymentStatusSelect2List: '/Lookup/PaymentStatus',
    GetSpBenSelect2ListBYEntityID: '/SpBeneficents/GetSpBeneficentsSelect2List',
    GetSponcerCategorySelect2List: '/Lookup/SponcerCategory',
    GetNationalitySelect2List: '/Lookup/Nationality',
    GetSpContractsNoSelect2List: '/SpContracts/GetContractNoSelect2List',
    GetContractStatusSelect2List: '/SpContracts/GetContractStatusSelect2List',
    GetBenefPaymentTypeSelect2List: '/SpContracts/GetBenefPaymentTypeSelect2List',
    GetGlPeriodYearsSelect2List: '/GlPeriodYears/GetGlPeriodYearsSelect2List',
    ChartTypeRevenueAndExpenses: '/ChartType/RevenueAndExpenses',
    GetCasesBranchSelect2List: '/Lookup/CasesBranch',
    GetCitySelect2List: '/Lookup/City',
    GetSPCasesEntitySelect2List: '/SocialCaseReport/GetSPCasesEntitySelect2List',
    GetRequestTypeSelect2List: '/Lookup/RequestType',
    GetAidRequestSourceSelect2List: '/Lookup/AidRequestSource',
    GetGenderSelect2List: '/Lookup/Gender',
    GetNameSelect2List: '/AidReques/GetNameSelect2',
    GetRequestTypeReportSelect2List: '/Lookup/RequestTypeReport',
    CaseStatusSelect2List: '/Lookup/CaseStatus',
    GenderSelect2List: '/Lookup/Gender',
    GetSpCaseSelect2List: '/SpCases/GetSpCaseSelect2List',
    GetScProjectStatusSelect2List: '/ScProject/GetScProjectStatusSelect2List',
    GetScProjectTypeSelect2List: '/ScProject/GetScProjectTypeSelect2List',
  };
}

